name: ui_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  badges: ^3.2.0
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  clippy_flutter: ^2.0.0-nullsafety.1

  flutter_lints: ^6.0.0

flutter:
  assets:
   - assets/images/A.png
   - assets/images/cart/
   - assets/images/categories/
   - assets/images/items/
   - assets/images/avatar/

  uses-material-design: true